<?php
$cols = 9;
$rows = 9;?>
<table class='custom_table' border=2>
    <?php for ($tr = 1; $tr <= $rows; $tr++):?>
        <tr <?php if ($tr % 2 == 0):?>class="row"<?php endif; ?>> {
            <?php for($td = 1; $td <= $cols; $td++):?>
                <td <?php if ($td % 2 == 0):?>class="cell"<?php endif;?>><?= $tr * $td ?>
</td>

            <?php endfor ?>
        </tr>
    <?php endfor ?>
</table>

