<table class='custom_table' border=2>
<?php
    $cols = 9;
    $rows = 9;
   
    for ($tr = 1; $tr <= $rows; $tr++)
    {
        if ($tr % 2 == 0) {
            echo "<tr class='row'>";
        }
        else {
            echo "<tr>";
        }
    for($td = 1; $td <= $cols; $td++)
        {
        if ($td % 2 == 0) { 
            echo "<td class='cell'>", $tr * $td, '</td>';
            }
        else {
            echo "<td>";
            }
        }
        echo "</td>";
    }
?>
</table>